on:
  push:
    branches:
      - master

name: Release Scene

jobs:
  release:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '10.x'

      - name: Install Dependencies
        run: npm install

      - name: Build Prod
        run: npm run build --prod

      - name: Zip & Tar gz Prod
        run: |
          cd ./dist/
          zip -r InterAACtionScene.zip *
          mv InterAACtionScene.zip ../
          tar -czvf InterAACtionScene.tar.gz *
          mv InterAACtionScene.tar.gz ../
          cd ../
      - name: Build prod Ligone
        run: npm run ligone

      - name: Zip prod Ligone
        run: |
          cd ./dist/
          zip -r InterAACtionSceneLigone.zip *
          mv InterAACtionSceneLigone.zip ../
      - name: Get Env
        run: |
          echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV
          echo "REPO_BASENAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
      - name: New tag
        id: new-tag
        run: |
          LATEST_RELEASE_INFO=$(curl -s https://api.github.com/repos/${{ env.REPO_NAME }}/releases/latest)
          NEW_VERSION_LINK=$(echo "$LATEST_RELEASE_INFO" | grep "browser_download_url.*InterAACtionScene*" | cut -d: -f2,3 | tr -d \")
          NEW_VERSION=$( echo "${NEW_VERSION_LINK}" | cut -d/ -f9)
          NEW_VERSION_NO_EXT=$( echo ${NEW_VERSION} | cut -d. -f1)
          NEW_VERSION_NAME=$(echo "$LATEST_RELEASE_INFO" | grep "name.*InterAACtionScene*" | cut -d: -f2,3 | tr -d \" | head -n 1 | tr -d \,)
          GET_TAG=$(echo "$NEW_VERSION_NAME" | cut -d " " -f3)
          TAG_1=$(echo "$GET_TAG" | cut -d. -f1)
          TAG_2=$(echo "$GET_TAG" | cut -d. -f2)
          TAG_3=$(echo "$GET_TAG" | cut -d. -f3)
          NEW_TAG=$(echo "$(( $TAG_3 + 1 ))")
          TAG="${TAG_1}.${TAG_2}.${NEW_TAG}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          
      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.new-tag.outputs.tag }}
          name: ${{ env.REPO_BASENAME }} ${{ steps.new-tag.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: "master"
          prerelease: true
          draft: false
          artifacts: "InterAACtionScene.zip,InterAACtionScene.tar.gz,InterAACtionSceneLigone.zip"
